name: Deploy

on:
  push:
    branches:
      - main  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.virtualekubdash.com
          username: test2@test2.virtualekubdash.com
          password: samisams@123
          protocol: ftp
          local-dir: ./  # Uploads all files from the root of the repository
          server-dir: /public_html/test2/  # Target directory on the server