name: Deploy

on:
  push:
    branches:
      - main  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Use the latest version
        with:
          server: ftp.virtualekubdash.com             # FTP server address
          username: test2@test2.virtualekubdash.com                              # FTP username (without domain)
          password: ${{ secrets.PASSWORD }}            # FTP password
          protocol: ftp                                # Use 'ftp' or 'ftps' as needed
          server-dir: /test1.virtualekubdash.com//                    # Adjust to the correct remote directory
          local-dir: ./                                # Local directory to upload from