name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /test1.virtualekubdash.com/  # Adjust this if needed
          local-dir: ./  # If your index.html is in the root, keep this as './'
          dry-run: false  # Change to true for testing without actual upload     
             
                 # Path to the public HTML directory