name: Deploy

on:
  push:
    branches:
      - main  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.virtualekubdash.com                      # FTP server address
          username: test1@test1.virtualekubdash.com           # FTP username
          password: ${{ secrets.PASSWORD }}                   # Use GitHub Secrets for FTP password
          local-dir: './'                                     # Local directory to deploy
          protocol: ftp                                       # Change to 'ftps' if SSL is enabled
          server-dir: /home/virtuada/test1.virtualekubdash.com/     
                 # Path to the public HTML directory